### ISSUE TITLE
Some of your vocabs are not ok; skos:broader VS skos:topConceptOf

### ISSUE THREAD

**Issue by sroertgen** [iqb-vocabs/Bildungsstandard2022-Deutsch-Primar#1]
Same error as described here: https://github.com/iqb-vocabs/Bildungstandard2023-erste-Fremdsprache-MSA/issues/1#issue-2099972131

Some of your top concepts are linking to the concept scheme with skos:broader instead of skos:topConceptOf

**Comment by nanoyan** [comment]
Thank you Steffen. We'll archive this repository
